listener 1883 0.0.0.0
protocol mqtt

listener 9001 0.0.0.0
protocol websockets

allow_anonymous true

persistence true
persistence_location /mosquitto/data/

log_dest file /mosquitto/log/mosquitto.log
log_dest stdout
log_type error
log_type warning
log_type notice
log_type information
log_timestamp true

connection_messages true

max_inflight_messages 1000
max_queued_messages 100000
message_size_limit 0

queue_qos0_messages false

sys_interval 10

autosave_interval 300
