use metrics::{counter, gauge, histogram};
use once_cell::sync::Lazy;
use std::sync::atomic::{AtomicU64, Ordering};
use std::time::Instant;

static MQTT_MESSAGES_RECEIVED: Lazy<metrics::Counter> = Lazy::new(|| {
    counter!("mqtt_messages_received_total", "Total MQTT messages received")
});

static MQTT_BYTES_RECEIVED: Lazy<metrics::Counter> = Lazy::new(|| {
    counter!("mqtt_bytes_received_total", "Total MQTT bytes received")
});

static CHANNEL_DATA_INSERTED: Lazy<metrics::Counter> = Lazy::new(|| {
    counter!("channel_data_inserted_total", "Total channel data points inserted")
});

static ANOMALIES_DETECTED: Lazy<metrics::Counter> = Lazy::new(|| {
    counter!("anomalies_detected_total", "Total anomalies detected", "type" => "voltage")
});

static PREDICTIONS_MADE: Lazy<metrics::Counter> = Lazy::new(|| {
    counter!("predictions_made_total", "Total capacity predictions made")
});

static ALERTS_GENERATED: Lazy<metrics::Counter> = Lazy::new(|| {
    counter!("alerts_generated_total", "Total alerts generated", "level" => "level1")
});

static ACTIVE_CHANNELS: Lazy<metrics::Gauge> = Lazy::new(|| {
    gauge!("active_channels", "Number of active channels")
});

static ABNORMAL_CHANNELS: Lazy<metrics::Gauge> = Lazy::new(|| {
    gauge!("abnormal_channels", "Number of abnormal channels")
});

static PAUSED_CHANNELS: Lazy<metrics::Gauge> = Lazy::new(|| {
    gauge!("paused_channels", "Number of paused channels")
});

static SYSTEM_CAPACITY_RATIO: Lazy<metrics::Gauge> = Lazy::new(|| {
    gauge!("system_capacity_ratio", "Average system capacity ratio")
});

static PREDICTION_LATENCY: Lazy<metrics::Histogram> = Lazy::new(|| {
    histogram!("prediction_latency_seconds", "Capacity prediction latency in seconds")
});

static MQTT_PROCESSING_LATENCY: Lazy<metrics::Histogram> = Lazy::new(|| {
    histogram!("mqtt_processing_latency_milliseconds", "MQTT message processing latency in ms")
});

static DB_INSERT_LATENCY: Lazy<metrics::Histogram> = Lazy::new(|| {
    histogram!("db_insert_latency_milliseconds", "Database insert latency in ms")
});

static REQUEST_COUNTER: AtomicU64 = AtomicU64::new(0);

pub fn init_metrics() {
    metrics::describe_counter!(
        "mqtt_messages_received_total",
        metrics::Unit::Count,
        "Total number of MQTT messages received from all cabinets"
    );
    metrics::describe_counter!(
        "mqtt_bytes_received_total",
        metrics::Unit::Bytes,
        "Total bytes received via MQTT"
    );
    metrics::describe_counter!(
        "channel_data_inserted_total",
        metrics::Unit::Count,
        "Total number of channel data points inserted into ClickHouse"
    );
    metrics::describe_counter!(
        "anomalies_detected_total",
        metrics::Unit::Count,
        "Total number of anomalies detected by type"
    );
    metrics::describe_counter!(
        "predictions_made_total",
        metrics::Unit::Count,
        "Total number of capacity predictions made"
    );
    metrics::describe_counter!(
        "alerts_generated_total",
        metrics::Unit::Count,
        "Total number of alerts generated by level"
    );
    metrics::describe_gauge!(
        "active_channels",
        metrics::Unit::Count,
        "Current number of active channels"
    );
    metrics::describe_gauge!(
        "abnormal_channels",
        metrics::Unit::Count,
        "Current number of abnormal channels"
    );
    metrics::describe_gauge!(
        "paused_channels",
        metrics::Unit::Count,
        "Current number of paused channels"
    );
    metrics::describe_gauge!(
        "system_capacity_ratio",
        metrics::Unit::Percent,
        "Average system capacity ratio"
    );
    metrics::describe_histogram!(
        "prediction_latency_seconds",
        metrics::Unit::Seconds,
        "Time taken to make a capacity prediction"
    );
    metrics::describe_histogram!(
        "mqtt_processing_latency_milliseconds",
        metrics::Unit::Milliseconds,
        "Time taken to process an MQTT message"
    );
    metrics::describe_histogram!(
        "db_insert_latency_milliseconds",
        metrics::Unit::Milliseconds,
        "Time taken to insert data into ClickHouse"
    );
}

pub fn record_mqtt_message(bytes: usize) {
    MQTT_MESSAGES_RECEIVED.increment(1);
    MQTT_BYTES_RECEIVED.increment(bytes as u64);
}

pub fn record_data_inserted(count: usize) {
    CHANNEL_DATA_INSERTED.increment(count as u64);
}

pub fn record_anomaly_detected(anomaly_type: &str) {
    counter!("anomalies_detected_total", "type" => anomaly_type.to_string()).increment(1);
}

pub fn record_prediction_made(start_time: Instant) {
    PREDICTIONS_MADE.increment(1);
    PREDICTION_LATENCY.record(start_time.elapsed().as_secs_f64());
}

pub fn record_alert_generated(level: &str) {
    counter!("alerts_generated_total", "level" => level.to_string()).increment(1);
}

pub fn record_mqtt_processing(start_time: Instant) {
    MQTT_PROCESSING_LATENCY.record(start_time.elapsed().as_millis() as f64);
}

pub fn record_db_insert(start_time: Instant, count: usize) {
    DB_INSERT_LATENCY.record(start_time.elapsed().as_millis() as f64);
    CHANNEL_DATA_INSERTED.increment(count as u64);
}

pub fn update_active_channels(count: u64) {
    ACTIVE_CHANNELS.set(count as f64);
}

pub fn update_abnormal_channels(count: u64) {
    ABNORMAL_CHANNELS.set(count as f64);
}

pub fn update_paused_channels(count: u64) {
    PAUSED_CHANNELS.set(count as f64);
}

pub fn update_system_capacity_ratio(ratio: f64) {
    SYSTEM_CAPACITY_RATIO.set(ratio);
}

pub fn increment_request_count() -> u64 {
    REQUEST_COUNTER.fetch_add(1, Ordering::SeqCst)
}

pub fn get_request_count() -> u64 {
    REQUEST_COUNTER.load(Ordering::SeqCst)
}

pub struct MetricsTimer {
    start: Instant,
    metric_type: MetricType,
}

#[derive(Debug, Clone, Copy)]
pub enum MetricType {
    Prediction,
    MqttProcessing,
    DbInsert,
}

impl MetricsTimer {
    pub fn new(metric_type: MetricType) -> Self {
        Self {
            start: Instant::now(),
            metric_type,
        }
    }

    pub fn finish(&self) {
        match self.metric_type {
            MetricType::Prediction => {
                PREDICTION_LATENCY.record(self.start.elapsed().as_secs_f64());
            }
            MetricType::MqttProcessing => {
                MQTT_PROCESSING_LATENCY.record(self.start.elapsed().as_millis() as f64);
            }
            MetricType::DbInsert => {
                DB_INSERT_LATENCY.record(self.start.elapsed().as_millis() as f64);
            }
        }
    }
}

impl Drop for MetricsTimer {
    fn drop(&mut self) {
        self.finish();
    }
}
